<<<<<<< HEAD
version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_URI=mysql://root:aagonzalez8@mysql/ecovida
      - MONGODB_URI=mongodb://mongo:27017/ecovida
    depends_on:
      - mysql
      - mongo
    networks:
      - my_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: aagonzalez8
      MYSQL_DATABASE: ecovida
    ports:
      - "3306:3306"
    networks:
      - my_network

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network:
=======
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ecovida
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: ecovida
      MYSQL_PASSWORD: ecovida
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  backend1:
    image: backend1  
    container_name: backend1
    ports:
      - "7001:7000"

  backend2:
    image: backend2 
    container_name: backend2
    ports:
      - "7002:7000"

volumes:
  mongodb_data:
  mysql_data:
  grafana_data:
>>>>>>> 8cd276d3bd106e19540aeb6efc104e574757a3fb
