version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_URI=mysql://root:aagonzalez8@mysql/ecovida
      - MONGODB_URI=mongodb://mongo:27017/ecovida
    depends_on:
      - mysql
      - mongo
    networks:
      - my_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: aagonzalez8
      MYSQL_DATABASE: ecovida
    ports:
      - "3306:3306"
    networks:
      - my_network

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network: